# SPDX-License-Identifier: GPL-3.0-or-later
"""KiCad .kicad_mod footprint file exporter."""

from pathlib import Path

from ..core.ipc7351 import FootprintResult, PadShape
from ..core.constants import (
    KICAD_LAYERS_SMD,
    KICAD_LAYERS_THT,
    KICAD_FP_VERSION,
    KICAD_GENERATOR_NAME,
    COURTYARD_LINE_WIDTH,
    SILKSCREEN_LINE_WIDTH,
    SILKSCREEN_OFFSET,
)

_THT_FAMILIES = {"dip", "sip", "tht", "axial", "radial"}


class KiCadModExporter:
    """Export a FootprintResult to KiCad .kicad_mod format."""

    def __init__(self, result: FootprintResult):
        self.result = result

    def export(self, output_path: str | Path) -> None:
        Path(output_path).write_text(self._generate())

    def to_string(self) -> str:
        return self._generate()

    def _generate(self) -> str:
        lines = [
            f'(footprint "{self._footprint_name()}"',
            f'  (version {KICAD_FP_VERSION})',
            f'  (generator "{KICAD_GENERATOR_NAME}")',
        ]
        pkg = self.result.package
        if pkg:
            lines.append(f'  (descr "{pkg.family} footprint generated by {KICAD_GENERATOR_NAME}-footprint-generator")')
        lines.append('  (layer "F.Cu")')
        lines.append('  (attr smd)')
        lines.extend(self._generate_pads())
        lines.extend(self._generate_courtyard())
        lines.extend(self._generate_silkscreen())
        lines.append(")")
        return "\n".join(lines)

    def _footprint_name(self) -> str:
        pkg = self.result.package
        if pkg and pkg.body:
            return f"{pkg.family}_{pkg.body.length.nominal:.2f}x{pkg.body.width.nominal:.2f}_{self.result.density}"
        return "unnamed_footprint"

    def _generate_pads(self) -> list[str]:
        lines = []
        for pad in self.result.pads:
            shape = "rect"
            if pad.shape == PadShape.CIRCLE:
                shape = "circle"
            elif pad.shape == PadShape.OBLONG:
                shape = "roundrect"
            elif pad.shape == PadShape.ROUNDED_RECTANGLE:
                shape = "roundrect"

            is_tht = self.result.package and self.result.package.family.lower() in _THT_FAMILIES
            layers = KICAD_LAYERS_THT if is_tht else KICAD_LAYERS_SMD

            lines.append(
                f'  (pad {pad.number} smd {shape} '
                f'(at {pad.position.x:.4f} {pad.position.y:.4f}) '
                f'(size {pad.width:.4f} {pad.height:.4f}) '
                f'(layers {layers}))'
            )
        return lines

    def _generate_courtyard(self) -> list[str]:
        cy = self.result.courtyard
        if not cy:
            return []
        w = COURTYARD_LINE_WIDTH
        return [
            f'  (fp_line (start {cy.x_min:.4f} {cy.y_min:.4f}) (end {cy.x_max:.4f} {cy.y_min:.4f}) (layer "F.CrtYd") (width {w}))',
            f'  (fp_line (start {cy.x_max:.4f} {cy.y_min:.4f}) (end {cy.x_max:.4f} {cy.y_max:.4f}) (layer "F.CrtYd") (width {w}))',
            f'  (fp_line (start {cy.x_max:.4f} {cy.y_max:.4f}) (end {cy.x_min:.4f} {cy.y_max:.4f}) (layer "F.CrtYd") (width {w}))',
            f'  (fp_line (start {cy.x_min:.4f} {cy.y_max:.4f}) (end {cy.x_min:.4f} {cy.y_min:.4f}) (layer "F.CrtYd") (width {w}))',
        ]

    def _generate_silkscreen(self) -> list[str]:
        pkg = self.result.package
        if not pkg or not pkg.body:
            return []
        bl = pkg.body.length.nominal / 2 + SILKSCREEN_OFFSET
        bw = pkg.body.width.nominal / 2 + SILKSCREEN_OFFSET
        w = SILKSCREEN_LINE_WIDTH
        return [
            f'  (fp_line (start {-bl:.4f} {-bw:.4f}) (end {bl:.4f} {-bw:.4f}) (layer "F.SilkS") (width {w}))',
            f'  (fp_line (start {bl:.4f} {-bw:.4f}) (end {bl:.4f} {bw:.4f}) (layer "F.SilkS") (width {w}))',
            f'  (fp_line (start {bl:.4f} {bw:.4f}) (end {-bl:.4f} {bw:.4f}) (layer "F.SilkS") (width {w}))',
            f'  (fp_line (start {-bl:.4f} {bw:.4f}) (end {-bl:.4f} {-bw:.4f}) (layer "F.SilkS") (width {w}))',
        ]

    def write_library(self, output_dir: str | Path, library_name: str = "generated") -> Path:
        lib_path = Path(output_dir) / f"{library_name}.pretty"
        lib_path.mkdir(parents=True, exist_ok=True)
        self.export(lib_path / f"{self._footprint_name()}.kicad_mod")
        return lib_path
