# SPDX-License-Identifier: GPL-3.0-or-later
"""KiCad .kicad_mod footprint file exporter."""

from pathlib import Path

from ..core.ipc7351 import FootprintResult, PadShape

SMD_LAYERS = '"F.Cu" "F.Paste" "F.Mask"'
THT_LAYERS = '"F.Cu" "B.Cu"'
THT_FAMILIES = {"dip", "sip", "tht", "axial", "radial"}


def _footprint_name(result: FootprintResult) -> str:
    pkg = result.package
    if pkg and pkg.body:
        return f"{pkg.family}_{pkg.body.length.nominal:.2f}x{pkg.body.width.nominal:.2f}_{result.density}"
    return "unnamed"


class KiCadModExporter:
    """Export a FootprintResult to KiCad .kicad_mod format."""

    def __init__(self, result: FootprintResult):
        self.result = result

    def export(self, path: str | Path) -> None:
        Path(path).write_text(self.to_string())

    def to_string(self) -> str:
        r = self.result
        pkg = r.package
        lines = [
            f'(footprint "{_footprint_name(r)}"',
            '  (version 20240101)',
            '  (generator "kicad-mil-ipc7351")',
        ]
        if pkg:
            lines.append(f'  (descr "{pkg.family} footprint generated by kicad-mil-ipc7351")')
        lines.append('  (layer "F.Cu")')
        lines.append('  (attr smd)')
        lines.extend(self._pads())
        lines.extend(self._courtyard())
        lines.extend(self._silkscreen())
        lines.extend(self._fab())
        lines.append(")")
        return "\n".join(lines)

    def _pads(self) -> list[str]:
        lines = []
        is_tht = self.result.package and self.result.package.family.lower() in THT_FAMILIES
        layers = THT_LAYERS if is_tht else SMD_LAYERS
        for p in self.result.pads:
            shape = "circle" if p.shape == PadShape.CIRCLE else "roundrect" if p.shape in (PadShape.OBLONG, PadShape.ROUNDED_RECTANGLE) else "rect"
            lines.append(f'  (pad {p.number} smd {shape} '
                         f'(at {p.position.x:.4f} {p.position.y:.4f}) '
                         f'(size {p.width:.4f} {p.height:.4f}) '
                         f'(layers {layers}))')
        return lines

    def _courtyard(self) -> list[str]:
        cy = self.result.courtyard
        if not cy:
            return []
        w = 0.05
        return [
            f'  (fp_line (start {cy.x_min:.4f} {cy.y_min:.4f}) (end {cy.x_max:.4f} {cy.y_min:.4f}) (layer "F.CrtYd") (width {w}))',
            f'  (fp_line (start {cy.x_max:.4f} {cy.y_min:.4f}) (end {cy.x_max:.4f} {cy.y_max:.4f}) (layer "F.CrtYd") (width {w}))',
            f'  (fp_line (start {cy.x_max:.4f} {cy.y_max:.4f}) (end {cy.x_min:.4f} {cy.y_max:.4f}) (layer "F.CrtYd") (width {w}))',
            f'  (fp_line (start {cy.x_min:.4f} {cy.y_max:.4f}) (end {cy.x_min:.4f} {cy.y_min:.4f}) (layer "F.CrtYd") (width {w}))',
        ]

    def _silkscreen(self) -> list[str]:
        pkg = self.result.package
        if not pkg or not pkg.body:
            return []
        bl = pkg.body.length.nominal / 2 + 0.1
        bw = pkg.body.width.nominal / 2 + 0.1
        w = 0.12
        return [
            f'  (fp_line (start {-bl:.4f} {-bw:.4f}) (end {bl:.4f} {-bw:.4f}) (layer "F.SilkS") (width {w}))',
            f'  (fp_line (start {bl:.4f} {-bw:.4f}) (end {bl:.4f} {bw:.4f}) (layer "F.SilkS") (width {w}))',
            f'  (fp_line (start {bl:.4f} {bw:.4f}) (end {-bl:.4f} {bw:.4f}) (layer "F.SilkS") (width {w}))',
            f'  (fp_line (start {-bl:.4f} {bw:.4f}) (end {-bl:.4f} {-bw:.4f}) (layer "F.SilkS") (width {w}))',
        ]

    def _fab(self) -> list[str]:
        pkg = self.result.package
        if not pkg or not pkg.body:
            return []
        bl, bw = pkg.body.length.nominal / 2, pkg.body.width.nominal / 2
        return [f'  (fp_circle (center {-bl:.4f} {-bw:.4f}) (end {-bl + 0.5:.4f} {-bw:.4f}) (layer "F.Fab") (width 0.1))']

    def write_library(self, output_dir: str | Path, name: str = "generated") -> Path:
        lib = Path(output_dir) / f"{name}.pretty"
        lib.mkdir(parents=True, exist_ok=True)
        self.export(lib / f"{_footprint_name(self.result)}.kicad_mod")
        return lib
