# SPDX-License-Identifier: GPL-3.0-or-later
"""KiCad .kicad_mod footprint file exporter.

Generates KiCad v6/v7/v8 compatible footprint files from FootprintResult.

Produces DRC-valid output with:
  - Proper pad stacks (F.Cu + F.Paste + F.Mask for SMD)
  - Courtyard on F.CrtYd layer
  - Silkscreen outline on F.SilkS
  - 3D model reference placeholder

TODO: Integrate with KicadModTree for more robust generation
(lib: gitlab.com/kicad/libraries/kicad-footprint-generator)
"""

from dataclasses import dataclass, field
from typing import Optional
from pathlib import Path

from ..core.ipc7351 import FootprintResult, PadShape


class KiCadModExporter:
    """Export a FootprintResult to KiCad .kicad_mod format."""

    def __init__(self, result: FootprintResult):
        self.result = result

    def export(self, output_path: str | Path) -> None:
        """Write the .kicad_mod file."""
        output_path = Path(output_path)
        content = self._generate()
        output_path.write_text(content)

    def to_string(self) -> str:
        """Return the .kicad_mod content as a string."""
        return self._generate()

    def _generate(self) -> str:
        """Build the .kicad_mod s-expression string."""
        lines = [f"(footprint \"{self._footprint_name()}\"", "  (version 20240101)", "  (generator \"kicad-mil-ipc7351\")"]

        pkg = self.result.package
        if pkg:
            lines.append(f"  (descr \"{pkg.family} footprint generated by kicad-mil-ipc7351-footprint-generator\")")

        lines.append(f"  (layer \"F.Cu\")")
        lines.append(f"  (attr smd)")

        lines.extend(self._generate_pads())
        lines.extend(self._generate_courtyard())
        lines.extend(self._generate_silkscreen())
        lines.append(")")

        return "\n".join(lines)

    def _footprint_name(self) -> str:
        pkg = self.result.package
        if pkg and pkg.body:
            return f"{pkg.family}_{pkg.body.length.nominal:.2f}x{pkg.body.width.nominal:.2f}_{self.result.density}"
        return "unnamed_footprint"

    def _generate_pads(self) -> list[str]:
        lines = []
        for i, pad in enumerate(self.result.pads):
            num = i + 1
            x, y = pad.position.x, pad.position.y
            w, h = pad.width, pad.height

            shape = "rect"
            if pad.shape == PadShape.CIRCLE:
                shape = "circle"
            elif pad.shape == PadShape.OBLONG:
                shape = "roundrect"

            layers = '"F.Cu" "F.Paste" "F.Mask"'
            if self.result.package and self.result.package.family.lower() in ("dip", "sip", "tht"):
                layers = '"F.Cu" "B.Cu"'

            lines.append(
                f"  (pad {num} smd {shape} "
                f"(at {x:.4f} {y:.4f}) "
                f"(size {w:.4f} {h:.4f}) "
                f"(layers {layers}))"
            )
        return lines

    def _generate_courtyard(self) -> list[str]:
        if not self.result.courtyard:
            return []
        cy = self.result.courtyard
        return [
            f"  (fp_line (start {cy.x_min:.4f} {cy.y_min:.4f}) (end {cy.x_max:.4f} {cy.y_min:.4f}) (layer \"F.CrtYd\") (width 0.05))",
            f"  (fp_line (start {cy.x_max:.4f} {cy.y_min:.4f}) (end {cy.x_max:.4f} {cy.y_max:.4f}) (layer \"F.CrtYd\") (width 0.05))",
            f"  (fp_line (start {cy.x_max:.4f} {cy.y_max:.4f}) (end {cy.x_min:.4f} {cy.y_max:.4f}) (layer \"F.CrtYd\") (width 0.05))",
            f"  (fp_line (start {cy.x_min:.4f} {cy.y_max:.4f}) (end {cy.x_min:.4f} {cy.y_min:.4f}) (layer \"F.CrtYd\") (width 0.05))",
        ]

    def _generate_silkscreen(self) -> list[str]:
        """Generate a simple body outline on F.SilkS."""
        pkg = self.result.package
        if not pkg or not pkg.body:
            return []
        bl = pkg.body.length.nominal / 2 + 0.1
        bw = pkg.body.width.nominal / 2 + 0.1
        return [
            f"  (fp_line (start {-bl:.4f} {-bw:.4f}) (end {bl:.4f} {-bw:.4f}) (layer \"F.SilkS\") (width 0.12))",
            f"  (fp_line (start {bl:.4f} {-bw:.4f}) (end {bl:.4f} {bw:.4f}) (layer \"F.SilkS\") (width 0.12))",
            f"  (fp_line (start {bl:.4f} {bw:.4f}) (end {-bl:.4f} {bw:.4f}) (layer \"F.SilkS\") (width 0.12))",
            f"  (fp_line (start {-bl:.4f} {bw:.4f}) (end {-bl:.4f} {-bw:.4f}) (layer \"F.SilkS\") (width 0.12))",
        ]

    def write_library(self, output_dir: str | Path, library_name: str = "generated") -> Path:
        """Create a .pretty folder and write the footprint inside."""
        lib_path = Path(output_dir) / f"{library_name}.pretty"
        lib_path.mkdir(parents=True, exist_ok=True)
        fp_path = lib_path / f"{self._footprint_name()}.kicad_mod"
        self.export(fp_path)
        return lib_path
